---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/about
  label: Acerca de mi
  create: all
  match: "**/*"
  templates:
  - profile-info
- type: directory
  path: content/blog-posts
  label: Artículos (blog posts)
  create: documents
  match: "**/*"
  templates:
  - template-for-blog-posts
upload_dir: statics
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
